#!/system/bin/sh

# Available frequencies (200000 400000 533333 800000 998400 1094400 1152000 1209600)

# Max
chmod 666 /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq 
echo "800000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
chmod 444 /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq 

# Min 

chmod 666 /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq 
echo "200000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
chmod 444 /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq 


#Governor  (interactive ondemand userspace powersave performance)
chmod 666 /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo "ondemand" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
chmod 444 /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor